### PR TITLE
corrections to Authentication for Bolusing section

### PR DESCRIPTION
**Pull request by snickerdoodleparent**
corrected header to Authentication and changed line 20 to line 28. (it was line 28 for my browser build)

### CODE REVIEW

**Comment by MikePlante1** [comment]
Thanks! I checked the code and see you're correct.

**Review by MikePlante1 — DISMISSED** [review]

**Comment by MikePlante1** [comment]
In testing this, I also noticed that it should be updated to say

```swift
if false && context.canEvaluatePolicy(.deviceOwnerAuthentication, error: &error) {
```

instead of

```swift
if false, context.canEvaluatePolicy(.deviceOwnerAuthentication, error: &error) {
```

Both work, but the second saves Xcode from doing an auto-correct for formatting.

If you want to update that in this PR, that'd be great... but if you'd rather not that's okay too and I can just submit a new PR for that after this one is accepted and merged.

**Comment by snickerdoodleparent** [comment]
Thanks for noticing that, I'll update it, then it'll be done in one.

**Comment by MikePlante1** [comment]
> Thanks for noticing that, I'll update it, then it'll be done in one.

Awesome, thank you!

**Review by MikePlante1 — APPROVED** [review]

**Review by Sjoerd-Bo3 — APPROVED** [review]
LGTM

**Comment by MikePlante1** [comment]
Merging with 2 approvals

**Pull request merged**
