### PR TITLE
update website logo

### PR DESCRIPTION
**Pull request by MikePlante1**
Preview [here](https://oidocs-mikeplante1.readthedocs.io/en/logo/)

Screenshot 2024-05-18 at 3 59 10 PM

### CODE REVIEW

**Comment by tmhastings** [comment]
Would it be possible to adjust the rest of the site colors to complement the new logo? Or does that involve adding another extension (attrs_inline)?

**Comment by MikePlante1** [comment]
> Would it be possible to adjust the rest of the site colors to complement the new logo? Or does that involve adding another extension (attrs_inline)?

I agree that the logo on the blue doesn't look great. I didn't look too hard into changing the color yet, but if we do want to change it, what color should we use?

Alternatively, we could just add a border and/or shadow to the logo to make it pop more from the background?

**Comment by Sjoerd-Bo3** [comment]
Can’t we just theme the whole website? Instead of only the border? That is looks a bit style to us?

**Comment by tmhastings** [comment]
@MikePlante1 What if we used the black background file so the rest of the menu wouldn't need adjusting? 

> Can’t we just theme the whole website? Instead of only the border? That is looks a bit style to us?

@Sjoerd-Bo3 I'm not sure we can without the proper Sphinx extension added. Ideally, I'd adjust all of the warnings/cautions/tips/etc, to match the color scheme, but that requires the ability to add custom colors. When I attempted to do so earlier, the "colon_fence" extension we have didn't support custom colors.

**Comment by MikePlante1** [comment]
How about this white border?

white border

**Comment by marionbarker** [comment]
To my eye the logo looks too big. But I agree we should have a logo there.

**Comment by tmhastings** [comment]
> How about this white border?
> 
> white border

I like the white. Let's update it to the white outline and I'll approve & merge

**Comment by MikePlante1** [comment]
> I like the white. Let's update it to the white outline and I'll approve & merge

Update is pushed.

> To my eye the logo looks too big. But I agree we should have a logo there.

I don't disagree, but I modeled it after [AAPS](https://androidaps.readthedocs.io/en/latest/) and [Nightscout](https://nightscout.readthedocs.io/en/latest/) docs.

**Review by tmhastings — APPROVED** [review]

**Pull request merged**
