### PR TITLE
🏗️ 💥 Migrate Site Generator to Mkdocs from Sphinx

### PR DESCRIPTION
**Pull request by ebouchut**
Today we use _Sphinx_ to create and generate the [trio-docs](https://docs.diy-trio.org) website.

🏗️ With this pull-request we switch to **[Mkdocs](https://www.mkdocs.org/)** (site generation engine) and [mkdocs-material](https://squidfunk.github.io/mkdocs-material/) (theme).

💥 This PR contains **breaking changes**.  
This is a different toolset.

## Updates

- [x] PDF export
- [x] Open external links in a new window (works on docs.diy-trio.org only)
- [x] Add CI/CD to build and publish the site automatically when pushing the dev branch to GitHub
- [x] Document how to install, build, and preview the site locally
- [x] Migrate the Table of Contents (TOC)
- [x] Migrate admonitions (rectangular text boxes)
- [x] Migrate images and their CSS classes
- [x] Migrate Maths formulae
- [x] No ePub export for now. No ad-hoc plugin found.

EDIT:
You can take a look at the [README](https://github.com/ebouchut/trio-docs/tree/mkdocs-material-migration?tab=readme-ov-file#readme) on this PR branch if you want to give this branch a whirl

TODO:
- [x] Purple instead of Blue
- [x] `TrioDocs` instead of `Trio documentation`
- [x] Move Top-menu to the top row to match _LoopDocs_ for `Home`, `Overview` (`Device Compatibility` could get moved into `Overview`), `Build/Update`, `User Settings`, `Optional Settings`, `Advanced Settings`, `Resources`.
- [x] Move the page sub-menu (page headings) to the right side to match _LoopDocs_
-  ~~Redirect old Sphinx URLs (with `en/latest/` prefix) to new ones (without)~~ (won't do)
- [x] Customise the 404 page
- [x] "Integrate" recently merged PRs:
  - [x] #62
  - #73 (not merged) 
  - [x] #74 
  - [x] #80 
  - #81 (not merged)
  - [x] #84
- [x] Merge this PR so that it makes into `dev`
- [x] Configure a [custom sub-domain on GitHub Pages](https://help.github.com/articles/adding-or-removing-a-custom-domain-for-your-github-pages-site)
  - [x] Add a `docs/CNAME` file containing `docs.diy-trio.org`
  - [x] Create the `gh-pages` on this GitHub repository (nightscout/trio-docs` like this:
    
    It does not exist yet but needs to be created once for the GitHub UI to pick it up in the branch chooser 🐓🥚 :-).
    Assuming that in your `trio-docs` repository, the:
      - `upstream` git remote denotes the `nightscout/trio-docs`
      - `origin` git remote  denotes your clone of the repository `YOUR_USERNAME_HERE/trio-docs`
    Use git remote -v  to check if this is the case.
   FIRST, MAKE SURE to have committed or stashed your current modifications.
     ```shell
     git checkout --orphan gh-pages
     git reset --hard
     git commit --allow-empty -m "fresh and empty gh-pages branch"
     git push upstream gh-pages
     ```
  - [x] Configure GitHub Pages
    CleanShot 2024-10-21 at 17 08 03@2x
  - [ ] [Verify the custom domain](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/verifying-your-custom-domain-for-github-pages)
    - Click Your user/company icon at the top right
    - Click Pages
    - Click the "`Add a Domain`" button
    - Enter `diy-trio.org`
    - Click the "`Add Domain`" button to confirm
    - Add a **`TXT`** DNS record as explained
    - Click **`Verify`** button once done and the DNS modification has been propagated
    > trio-gh-gh_pages-add_verified_domain-01
    
    > trio-gh-gh_pages-add_verified_domain-02

    
    > trio-gh-gh_pages-add_verified_domain-03
  - [x] Update the `docs.diy-trio.org` DNS record **after** deploying ~~so that it points to GitHub servers IP V4 and V6 addresses~~. It must be a `CNAME` record that points to `nightscout.github.io`  (as this is a custom subdomain, not an APEX (main domain)):
  ```
  docs.diy-trio.org.  1799    IN      CNAME   nightscout.github.io.
  ```
  - [x] [Enforce HHTPS](https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https)
  - [x] Secure the [custom domain](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#securing-your-custom-domain)

### CODE REVIEW

**Comment by ebouchut** [comment]
## Using  Keyboard Shortcuts  to Navigate pages and Search Results

- **next** page / **previous page**: `N`/`P`
- Open **Search** box: `/` or `F` or `S`
- In the search results page, use:
  -  ↑ ↓  the up  and down arrow keys to **navigate results**
  - ⏎  to **open** the currently selected **search result**
  - `<Esc>` or `<Tab>` to **close** the **search** box

ℹ️ **Source**: https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#keyboard-shortcuts

**Comment by ebouchut** [comment]
❓ Hey team, do we need to plan to redirect old _ReadTheDocs_ URLs?


**Example**:
> ```
> https://docs.diy-trio.org/en/latest/Getting-Started/Overview.html 
>   => https://docs.diy-trio.org/Getting-Started/Overview/
> ```

EDIT: Answered [here](https://discord.com/channels/1020905149037813862/1296176295352209451/1296503284625969254).

**Comment by ebouchut** [comment]
@tmhastings @MikePlante1 and Team

This PR is now ready for review.

I merged the recent PRs onto this PR branch.
Merging (into `dev`) will go smoothly because it is now a **fast-forward** without conflict resolution 😅.


## IMPORTANT

  - **Before** merging this PR
    - [x] **Disable** the **automation to publish** `dev` to _ReadTheDocs_ (RTD). 

  - **After** the merge
    - [x] The remaining tasks  (see [`TODO` in the description](https://github.com/nightscout/trio-docs/pull/83#issue-2592452878)) include configuring GitHub Pages and modifying a DNS entry. I can help with this if you need me.

**Review by marionbarker — DISMISSED** [review]
I have tested this locally using mkdocs serve as well as reviewing @ebouchut test display version online.

LGTM

**Comment by ebouchut** [comment]
🙏🏻 @marionbarker 

✅ I [fixed the typos](https://github.com/nightscout/trio-docs/pull/83/commits/bf9b1f4470fc143aee523e834ea56f335902217a) you found and reported on [Discord](https://discord.com/channels/1020905149037813862/1296176295352209451/1300128416133287937).

**Review by MikePlante1 — APPROVED** [review]
Superb job on this! Many thanks.

**Pull request merged**
